# Generated by Django 5.2.2 on 2025-06-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlogic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
